### ISSUE TITLE
Darkly - Input Icon Font Color

### ISSUE THREAD

**Issue by jslay88** [semantic-ui-forest/forest-themes#11]
Darkly's input icon (left in particular from what I currently have setup, likely right icon as well) font color is white. This should be grey. 

White icon on white text field input.

`<div class="ui left icon input"><i class="user icon"></i><input type="text"></div>`

**Comment by tarvos21** [comment]
@jslay88 Thanks, I have fixed the input icon's font color problem by removing the useless CSS code, and also updated Semantic-UI from 2.2.9 to 2.2.13.
