### ISSUE TITLE
Windows build script

### ISSUE THREAD

**Issue by rodryquintero** [semantic-ui-forest/forest-themes#13]
Build script only works on Linux.

**Comment by xiaohanyu** [comment]
@rodryquintero Will rewrite the build script in nodejs soon, sorry too busy in the last months.

**Comment by xiaohanyu** [comment]
Work in progress to migrate the build script from bash to node.

**Comment by xiaohanyu** [comment]
Finish the migration by 34aabc173081946b8e74f8a9d7ee59bf0bd9f6ff and 8eb920bf5918a62707824eb5670119491b321180.

Can help test if you have time, thanks!
