### ISSUE TITLE
Build Script Broken?

### ISSUE THREAD

**Issue by jimmyhales** [semantic-ui-forest/forest-themes#15]
I'm noticing at the end of the build script the line `git checkout . && git clean -fd` deletes all the themes the script just got done creating, thus leaving no themes. Am I missing something here?

**Comment by xiaohanyu** [comment]
Will fix that soon.

**Comment by jimmyhales** [comment]
很棒

**Comment by xiaohanyu** [comment]
Hi, @jimmyhales 

I just tried and it seems that the build script works well, 856ab33b6e58fd58b8c5faa164b15240da294d0d.

Anyway, I'm going to rewrite the build script in nodejs thus you can just run `npm build` to build all themes manually.

Thanks.

**Comment by xiaohanyu** [comment]
Hi, @jimmyhales ,

I just misunderstood your questions, actually, the build output was placed within the `forest-theme` repo instead of semantic-ui repo, so you can find the build assets on `forest-theme/dist` directory.

**Comment by jimmyspiffy** [comment]
I can see them in the forest-theme/dist, but this doesn't allow a user to customize them like I needed to. 

I removed git checkout . && git clean -fd from the script so the newly created folders remained in the semantic-ui directory. This way I could customize them further and use gulp to rebuild the css.

**Comment by xiaohanyu** [comment]
Hi, @jimmyhales 

I've just migrate the build script from bash script to node and integrate with npm, 8eb920bf5918a62707824eb5670119491b321180 and 34aabc173081946b8e74f8a9d7ee59bf0bd9f6ff.
