### ISSUE TITLE
Semantic 2.3 support

### ISSUE THREAD

**Issue by PapsOu** [semantic-ui-forest/forest-themes#16]
Hello @xiaohanyu, do you have planned to support semantic 2.3 ?

I think I've got a bug with pushable and theme `superhero`, mays be because you build this theme on semantic 2.2.13 an I'm using semantic 2.3.0

**Comment by xiaohanyu** [comment]
Yeah will definitely do that.

**Comment by xiaohanyu** [comment]
Hi, @PapsOu ,

This has been done in 856ab33b6e58fd58b8c5faa164b15240da294d0d.

I'll try to publish this to npm registry ASAP.
