### ISSUE TITLE
Opening tar.gz files?

### ISSUE THREAD

**Issue by rgdonohue** [semantic-ui-forest/forest-themes#7]
I've tried various utilities to open these files for the themes but keep getting errors when trying to unpack. Any suggestions? Or are the files corrupted somehow?

**Comment by xiaohanyu** [comment]
Oh really? I'll handle this soon.

**Comment by ghostsquad** [comment]
Which files are you referring to?

**Comment by rgdonohue** [comment]
I've tried a few off of [this website](http://semantic-ui-forest.com/templates/)

But specifically: [here](http://semantic-ui-forest.com/static/download/templates/bootstrap/navbar-fixed-top.tar.gz) and  [here](http://semantic-ui-forest.com/static/download/templates/bootstrap/starter-template.tar.gz)

**Comment by xiaohanyu** [comment]
Hi, @rgdonohue 

I'm too busy last week.

This issue has been fixed, it seems like this is due to a misuse of `git lfs`.

**Comment by rgdonohue** [comment]
Great! Looking forward to checking out the themes.
